#pragma config(Motor,  port2,           myMotor,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Motor 1 is given a power level of 127 (forward)
	motor[port2] = 127;
	// Wait for 1 second
	wait1Msec(1000);

	// Motor 1 is given a power level of -127 (reverse)
	motor[port2] = -127;
	// Wait for 1 second
	wait1Msec(1000);
}
